# Generated by Django 4.2.4 on 2025-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_paid_alter_rental_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('budget', 'Budget'), ('midrange', 'Midrange'), ('premium', 'Premium/SUV')], default='budget', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
