# Generated by Django 4.2.4 on 2025-06-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
